from collections.abc import Sequence
from typing import Any, overload

class NativeError(Exception): ...

class NativeLink:
    table_key: int
    object_key: int

class NativeTimestamp:
    seconds: int
    nanoseconds: int

class NativeObjectId:
    value: str

class NativeDecimal128:
    value: str

class NativeResults(Sequence[dict[str, object]]):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> dict[str, object]: ...
    @overload
    def __getitem__(self, index: slice) -> Sequence[dict[str, object]]: ...

class NativeRealm:
    def __init__(self, path: str, key: bytes = ...) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def core_version(self) -> str: ...
    def close(self) -> None: ...
    def schema(self) -> list[dict[str, Any]]: ...
    def table_names(self) -> list[str]: ...
    def count(self, table_name: str) -> int: ...
    def all(self, table_name: str) -> NativeResults: ...
    def query(self, table_name: str, query: str, *parameters: object) -> NativeResults: ...
    def record(self, table_key: int, object_key: int) -> dict[str, object]: ...
